FROM node:16.14.2-alpine
WORKDIR /app

ARG SET_MYSQL_PASSWORD
ARG SET_OSS_ACCESSKEY_ID
ARG SET_OSS_ACESSKEY_SECRET
ARG SET_OSS_BUCKET_NAME
ARG SET_OSS_ENDPOINT

ENV TZ="Asia/Shanghai"
ENV MYSQL_HOST=localhost
ENV MYSQL_USERNAME=root
ENV MYSQL_PASSWORD=${SET_MYSQL_PASSWORD}
ENV MYSQL_PORT=3306
ENV REDIS_HOST=localhost
ENV REDIS_PORT=6379
ENV OSS_ACCESSKEY_ID=${SET_OSS_ACCESSKEY_ID}
ENV OSS_ACESSKEY_SECRET=${SET_OSS_ACESSKEY_SECRET}
ENV OSS_BUCKET_NAME=${SET_OSS_BUCKET_NAME}
ENV OSS_ENDPOINT=${SET_OSS_ENDPOINT}

COPY . .

RUN npm install --registry=https://registry.npm.taobao.org
RUN npm install pm2 -g
RUN npm run build
RUN npm prune --production

EXPOSE 7001

ENTRYPOINT ["npm", "run", "pmstart"]
